FROM node:20-alpine

WORKDIR /usr/src/app

ARG DATABASE_URL
COPY ./packages ./packages
COPY ./package-lock.json ./package-lock.json

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/web ./apps/web

RUN npm install
RUN npm run db:generate

EXPOSE 3000

CMD ["npm","run","start:web"]